name: Main CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      python-versions: '["3.10", "3.11", "3.12"]'
      operating-systems: '["ubuntu-latest"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  #  build-and-push:
#    needs: tests
#    uses: ./.github/workflows/build-and-push.yml
#    secrets:
#      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
#      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  update-readme:
#    needs: tests
    uses: ./.github/workflows/update-readme.yml
    secrets:
      personal_pat: ${{ secrets.ATTICUS_PAT }}

#  release:
#    needs: tests
#    uses: ./.github/workflows/release.yml
#    with:
#      python-version: "3.11"
